import type { Metadata } from "next";
import "./globals.scss";
import "@/styles/reset.scss";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "قسطا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
