import type { Metadata } from "next";
import "./globals.scss";
import "@/styles/reset.scss";

export const metadata: Metadata = {
  title: "قسطا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
